import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/ui/components/sidebar";
import { inter } from "../ui/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${inter.className} flex`}>
          <div>
            <SideBar/>
          </div>
          <div className="bg-stone-300">
            {children}
          </div>
        </body>
    </html>
  );
}
